# Form implementation generated from reading ui file 'c:\Users\26071\Desktop\Class-Widgets\ui\yukimura\dark\widget-countdown.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 125)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 65536))
        self.progressBar = ProgressBar(parent=Form)
        self.progressBar.setGeometry(QtCore.QRect(20, 90, 161, 5))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 5))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 6))
        self.progressBar.setStyleSheet("")
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar.setUseAni(True)
        self.progressBar.setVal(0.0)
        self.progressBar.setObjectName("progressBar")
        self.activity_countdown_title = QtWidgets.QLabel(parent=Form)
        self.activity_countdown_title.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.activity_countdown_title.setFont(font)
        self.activity_countdown_title.setStyleSheet("color: rgba(255, 255, 255, 150);\n"
"font-weight: bold;")
        self.activity_countdown_title.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.activity_countdown_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.activity_countdown_title.setObjectName("activity_countdown_title")
        self.activity_countdown = QtWidgets.QLabel(parent=Form)
        self.activity_countdown.setGeometry(QtCore.QRect(20, 40, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.activity_countdown.setFont(font)
        self.activity_countdown.setStyleSheet("border: none;\n"
"color: rgba(255, 255, 255, 255);\n"
"font-weight: bold")
        self.activity_countdown.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.activity_countdown.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.activity_countdown.setObjectName("activity_countdown")
        self.backgnd = QtWidgets.QLabel(parent=Form)
        self.backgnd.setGeometry(QtCore.QRect(10, 10, 181, 91))
        self.backgnd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(50, 25, 35, 255), stop:1 rgba(15, 18, 22, 255));\n"
"border-radius: 8px")
        self.backgnd.setText("")
        self.backgnd.setObjectName("backgnd")
        self.img = QtWidgets.QLabel(parent=Form)
        self.img.setGeometry(QtCore.QRect(100, 10, 91, 91))
        self.img.setStyleSheet("")
        self.img.setPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../img/5.png"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.backgnd.raise_()
        self.img.raise_()
        self.progressBar.raise_()
        self.activity_countdown_title.raise_()
        self.activity_countdown.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "活动倒计时"))
        self.activity_countdown_title.setText(_translate("Form", "倒计时"))
        self.activity_countdown.setText(_translate("Form", "00:00"))
from qfluentwidgets import ProgressBar
