# Form implementation generated from reading ui file 'c:\Users\26071\Desktop\Class-Widgets\ui\yukimura\dark\widget-countdown-custom.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 125)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 65536))
        self.countdown_custom_title = QtWidgets.QLabel(parent=Form)
        self.countdown_custom_title.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.countdown_custom_title.setFont(font)
        self.countdown_custom_title.setStyleSheet("color: rgba(255, 255, 255, 150);\n"
"font-weight: bold;")
        self.countdown_custom_title.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.countdown_custom_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.countdown_custom_title.setObjectName("countdown_custom_title")
        self.custom_countdown = QtWidgets.QLabel(parent=Form)
        self.custom_countdown.setGeometry(QtCore.QRect(20, 30, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.custom_countdown.setFont(font)
        self.custom_countdown.setStyleSheet("border: none;\n"
"color: rgba(255, 255, 255, 255);\n"
"font-weight: bold")
        self.custom_countdown.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.custom_countdown.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.custom_countdown.setObjectName("custom_countdown")
        self.backgnd = QtWidgets.QLabel(parent=Form)
        self.backgnd.setGeometry(QtCore.QRect(10, 10, 181, 91))
        self.backgnd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(50, 25, 35, 255), stop:1 rgba(15, 18, 22, 255));\n"
"border-radius: 8px")
        self.backgnd.setText("")
        self.backgnd.setObjectName("backgnd")
        self.img = QtWidgets.QLabel(parent=Form)
        self.img.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.img.setStyleSheet("")
        self.img.setPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../img/2.png"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.backgnd.raise_()
        self.img.raise_()
        self.countdown_custom_title.raise_()
        self.custom_countdown.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "自定义倒计时"))
        self.countdown_custom_title.setText(_translate("Form", "距离 中考 还有"))
        self.custom_countdown.setText(_translate("Form", "300 天"))
