# Form implementation generated from reading ui file 'c:\Users\26071\Desktop\Class-Widgets\ui\yukimura\dark\widget-current-activity.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(360, 125)
        Form.setMinimumSize(QtCore.QSize(0, 100))
        Form.setMaximumSize(QtCore.QSize(16777215, 65536))
        self.subject = QtWidgets.QPushButton(parent=Form)
        self.subject.setGeometry(QtCore.QRect(10, 40, 341, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.subject.setFont(font)
        self.subject.setStyleSheet("QPushButton {\n"
"        qproperty-iconSize: 24px;\n"
"        color: white;\n"
"        border: none;\n"
"        color: rgba(255, 255, 255, 255);\n"
"        font-weight: bold\n"
"    }\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../../../img/it.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.subject.setIcon(icon)
        self.subject.setIconSize(QtCore.QSize(24, 24))
        self.subject.setObjectName("subject")
        self.blurEffect = QtWidgets.QLabel(parent=Form)
        self.blurEffect.setGeometry(QtCore.QRect(170, 40, 35, 35))
        self.blurEffect.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"border-radius:20px")
        self.blurEffect.setText("")
        self.blurEffect.setObjectName("blurEffect")
        self.sub_title = QtWidgets.QLabel(parent=Form)
        self.sub_title.setGeometry(QtCore.QRect(30, 0, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sub_title.setFont(font)
        self.sub_title.setStyleSheet("color: rgba(255, 255, 255, 150);\n"
"font-weight: bold;")
        self.sub_title.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.sub_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sub_title.setObjectName("sub_title")
        self.backgnd = QtWidgets.QLabel(parent=Form)
        self.backgnd.setGeometry(QtCore.QRect(10, 10, 341, 91))
        self.backgnd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(50, 25, 35, 255), stop:1 rgba(15, 18, 22, 255));\n"
"border-radius: 8px")
        self.backgnd.setText("")
        self.backgnd.setObjectName("backgnd")
        self.img = QtWidgets.QLabel(parent=Form)
        self.img.setGeometry(QtCore.QRect(30, 10, 91, 91))
        self.img.setStyleSheet("")
        self.img.setPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../img/1.png"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.backgnd.raise_()
        self.img.raise_()
        self.blurEffect.raise_()
        self.sub_title.raise_()
        self.subject.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "当前活动"))
        self.subject.setText(_translate("Form", "  测试"))
        self.sub_title.setText(_translate("Form", "当前活动"))
