# Form implementation generated from reading ui file 'c:\Users\26071\Desktop\Class-Widgets\ui\yukimura\dark\widget-weather.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(200, 125)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 65536))
        self.current_city = QtWidgets.QLabel(parent=Form)
        self.current_city.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.current_city.setFont(font)
        self.current_city.setStyleSheet("color: rgba(255, 255, 255, 185);\n"
"font-weight: bold;")
        self.current_city.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.current_city.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.current_city.setObjectName("current_city")
        self.backgnd = QtWidgets.QLabel(parent=Form)
        self.backgnd.setGeometry(QtCore.QRect(10, 10, 181, 91))
        self.backgnd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(40, 60, 110, 245), stop:1 rgba(75, 175, 245, 245));\n"
"border-radius: 8px")
        self.backgnd.setText("")
        self.backgnd.setObjectName("backgnd")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 141, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.weather_icon = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weather_icon.sizePolicy().hasHeightForWidth())
        self.weather_icon.setSizePolicy(sizePolicy)
        self.weather_icon.setText("")
        self.weather_icon.setPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../../../img/weather/0.svg"))
        self.weather_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather_icon.setObjectName("weather_icon")
        self.horizontalLayout_2.addWidget(self.weather_icon)
        self.temperature = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperature.sizePolicy().hasHeightForWidth())
        self.temperature.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.temperature.setFont(font)
        self.temperature.setStyleSheet("border: none;\n"
"color: rgba(255, 255, 255, 255);\n"
"font-weight: bold")
        self.temperature.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.temperature.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.temperature.setObjectName("temperature")
        self.horizontalLayout_2.addWidget(self.temperature)
        self.img = QtWidgets.QLabel(parent=Form)
        self.img.setGeometry(QtCore.QRect(100, 10, 91, 91))
        self.img.setStyleSheet("")
        self.img.setPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../img/4.png"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.backgnd.raise_()
        self.img.raise_()
        self.current_city.raise_()
        self.horizontalLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "天气"))
        self.current_city.setText(_translate("Form", "当前城市"))
        self.temperature.setText(_translate("Form", "114℉"))
