# Form implementation generated from reading ui file 'c:\Users\26071\Desktop\Class-Widgets\ui\yukimura\dark\widget-time.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(210, 125)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(16777215, 65536))
        self.date_text = QtWidgets.QLabel(parent=Form)
        self.date_text.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.date_text.setFont(font)
        self.date_text.setStyleSheet("color: rgba(255, 255, 255, 150);\n"
"font-weight: bold;")
        self.date_text.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.date_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.date_text.setObjectName("date_text")
        self.day_text = QtWidgets.QLabel(parent=Form)
        self.day_text.setGeometry(QtCore.QRect(30, 40, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.day_text.setFont(font)
        self.day_text.setStyleSheet("border: none;\n"
"color: rgba(255, 255, 255, 255);\n"
"font-weight: bold")
        self.day_text.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.day_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.day_text.setObjectName("day_text")
        self.backgnd = QtWidgets.QLabel(parent=Form)
        self.backgnd.setGeometry(QtCore.QRect(10, 10, 191, 91))
        self.backgnd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(50, 25, 35, 255), stop:1 rgba(15, 18, 22, 255));\n"
"border-radius: 8px")
        self.backgnd.setText("")
        self.backgnd.setObjectName("backgnd")
        self.img = QtWidgets.QLabel(parent=Form)
        self.img.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.img.setStyleSheet("")
        self.img.setPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../img/1.png"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.backgnd.raise_()
        self.img.raise_()
        self.date_text.raise_()
        self.day_text.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "时间"))
        self.date_text.setText(_translate("Form", "2025 年  13 月"))
        self.day_text.setText(_translate("Form", "32 日 周二"))
