# Form implementation generated from reading ui file 'c:\Users\26071\Desktop\Class-Widgets\ui\yukimura\dark\widget-next-activity.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(290, 125)
        Form.setMinimumSize(QtCore.QSize(0, 100))
        Form.setMaximumSize(QtCore.QSize(16777215, 65536))
        self.next_subtitle = QtWidgets.QLabel(parent=Form)
        self.next_subtitle.setGeometry(QtCore.QRect(40, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.next_subtitle.setFont(font)
        self.next_subtitle.setStyleSheet("color: rgba(255, 255, 255, 150);\n"
"font-weight: bold;")
        self.next_subtitle.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.next_subtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.next_subtitle.setObjectName("next_subtitle")
        self.next_lesson_text = QtWidgets.QLabel(parent=Form)
        self.next_lesson_text.setGeometry(QtCore.QRect(40, 40, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.next_lesson_text.setFont(font)
        self.next_lesson_text.setStyleSheet("border: none;\n"
"color: rgba(255, 255, 255, 255);\n"
"font-weight: bold")
        self.next_lesson_text.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.next_lesson_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.next_lesson_text.setObjectName("next_lesson_text")
        self.backgnd = QtWidgets.QLabel(parent=Form)
        self.backgnd.setGeometry(QtCore.QRect(10, 10, 271, 91))
        self.backgnd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(50, 25, 35, 255), stop:1 rgba(15, 18, 22, 255));\n"
"border-radius: 8px")
        self.backgnd.setText("")
        self.backgnd.setObjectName("backgnd")
        self.img = QtWidgets.QLabel(parent=Form)
        self.img.setGeometry(QtCore.QRect(190, 10, 91, 91))
        self.img.setStyleSheet("")
        self.img.setPixmap(QtGui.QPixmap("c:\\Users\\26071\\Desktop\\Class-Widgets\\ui\\yukimura\\dark\\../img/4.png"))
        self.img.setScaledContents(True)
        self.img.setObjectName("img")
        self.backgnd.raise_()
        self.img.raise_()
        self.next_subtitle.raise_()
        self.next_lesson_text.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "更多活动"))
        self.next_subtitle.setText(_translate("Form", "接下来"))
        self.next_lesson_text.setText(_translate("Form", "测试测试"))
